// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftkmzykwyjjsdbkpdhlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0a216eWt3eWpqc2Ria3BkaGx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYwNDczMjgsImV4cCI6MjEwMTYyMzMyOH0.61UUzYA6H-sgjWfovJ6gi0AbMeQyU-I45eDjhxCV8ME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});